# Jets::Config.project_namespace is special value results in using the project namespace. Example :
# table_namespace: <%= Jets.config.project_namespace %>
# This is the default value.

development:
  table_namespace: <%= Jets.config.table_namespace %>
  # More examples:
  # table_namespace: demo-dev

test:
  # table_namespace: proj # do not include the env
  endpoint: http://localhost:8000
  table_namespace: <%= Jets.config.table_namespace %>

production:
  table_namespace: <%= Jets.config.table_namespace %>
